### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
I even uploaded images to https://hub.docker.com/r/schmmd/openie-standalone/tags/.  Once this passes code review, I will add instructions for how to run Open IE using docker to the README.

**Review by aimichal — APPROVED** [review]
Looks okay to me.

You mentioned offline that there were some other surprises you discovered. More changes to come?

**Comment by schmmd** [comment]
@aimichal I mentioned surprised you had seen, such as https://github.com/allenai/openie-standalone/pull/15/files#diff-6f231a23d0439bfb6acf851b83a1f7a1R19.

**Comment by aimichal** [comment]
Okay, feel free to merge.

**Review by jkinkead — APPROVED** [review]
LGTM!

**Pull request merged**
